### PR TITLE
prevent scrolling to top

### PR DESCRIPTION
**Pull request by phelipe**
Sometimes when click to change tab it scroll page to top. I think this change prevent scrolling to top,

### CODE REVIEW

**Comment by rvanhorn** [comment]
Hello,

Thanks for the PR! 

I'm unable to replicate the issue, can you link me to an example please. 

https://user-images.githubusercontent.com/41927843/103468310-9c2be200-4d0c-11eb-8639-d19296c2d2ef.mp4

**Comment by phelipe** [comment]
Sure! This is a gif about the problem:
href

Using data-target there is no problem
data

**Comment by rvanhorn** [comment]
How interesting, it looks like the tab isn't changing at all.  

I'd really like to look at the code itself if its publicly available.

**Comment by phelipe** [comment]
I created a MWE to show the problem. Code bellow
[starter.zip](https://github.com/rvanhorn/hugo-dynamic-tabs/files/5761811/starter.zip)

**Comment by rvanhorn** [comment]
Sorry for the delay. 

Looks like is an issue with the version of jQuery you are using as I was able to "fix" it by either using the version recommend for [Bootstrap 4.3.1](https://getbootstrap.com/docs/4.3/getting-started/introduction/) or by using Bootstrap 4.5.3 and its recommend version for jQuery. Seems there is some compatibility issues when using Bootstrap 4.3.1 and jQuery 3.4.1

**Pull request closed without merging**
